export const ROOT_DIR = '.infio_json_db'
export const COMMAND_DIR = 'commands'
export const CHAT_DIR = 'qai'
export const CUSTOM_MODE_DIR = 'custom_modes'
export const INITIAL_MIGRATION_MARKER = '.initial_migration_completed'
